{application,npcrwlr,
             [{applications,[kernel,stdlib,elixir,logger,poolboy,mongodb,
                             httpoison,floki,gollum]},
              {description,"npcrwlr"},
              {modules,['Elixir.Database','Elixir.NPCrwlr','Elixir.Parser',
                        'Elixir.Scraper']},
              {registered,[]},
              {vsn,"0.1.0"},
              {extra_applications,[logger]}]}.
